name: Tagging on PR Merge

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  tag:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'develop'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Remove previous tags
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git fetch --prune origin "+refs/tags/*:refs/tags/*"
        git tag -l | xargs -n 1 git push --delete origin
        git tag -l | xargs git tag -d

    - name: Create and push new tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        NEW_TAG="v1.0.0"
        git tag $NEW_TAG
        git push origin $NEW_TAG
